## 将此更改为您的插件的名称.
name: DyeBench

## 将此更改为您的用户名.
author: JasperChaseTOQ

## 将其更改为对您的插件有意义但简短的描述.
description: A generic Slimefun4-Addon

## 将其更改为扩展 JavaPlugin 的类的路径.
main: me.jasperchasetoq.dyebench.DyeBench

## 您可以将其更改为链接到您的网站或存储库。 如果需要，您也可以删除此行。
website: https://github.com/Slimefun/Addon-Template

## 此值会自动替换为 pom.xml 文件中指定的版本。
## 不要改变这个.
version: ${project.version}

## 这是运行插件所需的最低 minecraft 版本.
api-version: 1.17

## 这是必需的，并将 Slimefun 标记为插件依赖项.
depend:
- Slimefun