name: Java CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: 设置 JDK 17
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17
    - name: 使用 Maven 构建
      run: mvn package --file pom.xml
